import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const { version } = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
const header = `// ==UserScript==
// @name         Google Meet Transcript
// @namespace    https://github.com/mlajkim/tampermonkey-userscripts
// @version      ${version}
// @description  Automatically capture captions, back up every 30 minutes, and download on leaving.
// @author       mlajkim
// @match        https://meet.google.com/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

// Generated by npm run build. Edit src/ and rebuild.
`;
const sources = [];
for (const path of ["src/transcript.js", "src/captions.js", "src/recovery.js", "src/meeting.js", "src/app.js"]) {
  const source = await readFile(new URL(path, root), "utf8");
  sources.push(`// ${path}\n` + source.replace(/^import .+;\n/gmu, "").replace(/^export /gmu, ""));
}
const output = `${header}\n(() => {\n"use strict";\n\n${sources.join("\n")}\n})();\n`;
await writeFile(new URL("google-meet-transcript.user.js", root), output);
console.log("Built google-meet-transcript.user.js");
